#!/bin/sh
export JAVA_HOME=/opt/jdk1.8.0_221
export ANT_HOME=/opt/apache-ant-1.10.6
export PATH=$JAVA_HOME/bin:$PATH
export PATH=$ANT_HOME/bin:$PATH
java -jar bin/DuckPondBarHeadless.jar DuckPond.lxp

